# Generated by Django 3.0.4 on 2020-03-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
                ('imageFileName', models.CharField(default='food_img2.jpg', max_length=30)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('imageFileName', models.CharField(default='profilepic4.png', max_length=30)),
                ('email', models.EmailField(default='homechef302020@gmail.com', max_length=254)),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('address', models.TextField()),
                ('timings', models.TextField(default='09AM - 06PM')),
            ],
        ),
    ]
