# Generated by Django 3.0.4 on 2020-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='vendors',
            field=models.ManyToManyField(to='homechef.Vendor'),
        ),
    ]
