# Generated by Django 3.0.4 on 2020-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechef', '0002_fooditem_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='food_items',
            field=models.ManyToManyField(to='homechef.FoodItem'),
        ),
    ]
