# Generated by Django 3.0.4 on 2020-03-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechef', '0004_auto_20200326_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
