# Generated by Django 3.0.8 on 2020-07-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechef', '0006_auto_20200717_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
