# Generated by Django 3.0.8 on 2020-07-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homechef', '0011_auto_20200718_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendorobj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homechef.Vendor'),
        ),
    ]
