# Generated by Django 3.0.8 on 2020-07-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homechef', '0012_orderitem_vendorobj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(default=10.0),
        ),
    ]
