# Generated by Django 3.0.8 on 2020-07-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homechef', '0014_billingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
